### ISSUE TITLE
Publication Details Page User Interface

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-ui#117]
- As a curator
- I need a user interface such that when I visit the url https://www.ebi.ac.uk/gwas/depo-curation/publications/{pubmedId}
- A detailed page of the corresponding publication is displayed similar to the [Submission detailed page ](https://www.ebi.ac.uk/gwas/depo-curation/submissions/62ba918f8a6cfa000162e5d2 )

<img width="1549" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFVXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8605905fae3077708975e59a83b050dca906c51c/Screenshot%202024-01-31%20at%2013.24.43.png" alt="Screenshot 2024-01-31 at 13.24.43.png" />

- Rule 1: The first entry point to this UI should be whenever a row on the [Publication page](https://www.ebi.ac.uk/gwas/depo-curation/publications) is clicked 
- Rule 2: The second entry entry point to this UI should be whenever a PMID on the [Submission page](https://www.ebi.ac.uk/gwas/depo-curation/submissions) is clicked 
- Rule 3: The url of the publication detail view should be - https://www.ebi.ac.uk/gwas/depo-curation/publications/<pubmedId>
- Rule 4: All publications should have this detailed page including those without associated submissions
- Rule 5: The tabs are: Details, Studies, Samples, Associations, Literature, and Notes tab

**DETAILS TAB:**

- 1. Details tab will feature 3 sections:
- 2. The publication details section 
- 3. The submission details section 
- 4. The Publication Event history section (which will be implemented later)  
- 5. For publications that have no submission, the submission section of the details tab will be empty 
- 6. For publications that have more than one submission, the submission section of the details tab will display all the submissions 

**LITERATURE TAB:**

- The UI should be as shown below 
- The upload UI of the edit submission can be re-used as it is
- This will feature multiple file upload with drop-zone style UI
- Horizontal table of uploaded files should be positioned below the file upload area, showing file name
- The last 2 columns should be for delete, and download  as shown in the Mock UI

<img width="1845" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXVNQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--781e7c2a17ee321cb68b26ee1f2af4ac6c377e2a/literature-file.jpg" alt="literature-file.jpg" />

**Comment by ala-ebi** [comment]
add curator and curation status to the publication details card
replace the Associations tab with Literature
change the tracking section to a tab

**Comment by ljwh2** [comment]
waitiing for ftp issues with literature to be resolved before releasing to sandbox

**Comment by ljwh2** [comment]
Feedback from testing: https://docs.google.com/document/d/1hlihpeERA0beyRoMJT5OvzIHWaJNRGjamxCdOvTSUy4/edit?usp=sharing
