### ISSUE TITLE
Feedback from testing Publication import

### ISSUE THREAD

**Issue by ala-ebi** [EBISPOT/gwas-curation-ui#120]
- [x] add curation status "Awaiting submission" to imported publications
- [x] add curator "Level 1 curator" to imported publications
- [x] add curation status "Submission complete" to linked publication
- [x] add curator "Level 2 curator" to linked publications
- [x] add Publication Title and Author in the submission linking dialog, under title
- [x] confirmation dialog before linking submission to publication
- [x] Include the PMID column when selecting the Include submission having PMID
- [x] turn @PostConstruct into an API for filling submitter field in Publication

**Comment by ljwh2** [comment]
@Santhi1901 please test

**Comment by Santhi1901** [comment]
I have added some comments to the document.

**Comment by ala-ebi** [comment]
added comments to doc
