### ISSUE TITLE
Changes to submissions table 

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-ui#13]
- UX Feedback: https://bit.ly/3bk4HA3
- In addition to Elliot's Point 2, when 20 is selected the table data display area shown should become longer displaying the full size and not capped at a fixed vertical size 
- Need to centrally manage the font sizes to ensure consistency, the font size on table in submission seems to be about 1px bigger than others 
- Possibility of reducing vertical padding of the table cells slightly to accomodate more data display on first view 
- History Table and submissions table be made striped / zebra 
- Vertical Filter area be implemented as in mock 
- Table Head / Description as shown in the mock be implemented
- Submission Id text be removed and replaced with lickable table row (Done)
- The columns displayed presently looks great and can be left as it is (No need to alter to what we have in the images below)

![1.jpg](https://images.zenhubusercontent.com/5f0f4126d974dfe9149c1910/9ce38cb4-f7de-47c2-97c4-8ab29e32fcd7)

![2.jpg](https://images.zenhubusercontent.com/5f0f4126d974dfe9149c1910/6e6fb796-9917-4b34-9839-4a06086bda4c)

**Comment by ala-ebi** [comment]
Note to self:
1. done
2. font for the table and details page are the same 14px, they may seem bigger in the former due to the uppercase letters.
3. good point. cell padding reduced from 4 to 2px.
4. done
5. to do
6. to do
7. done
8. okay
