### ISSUE TITLE
Submission History / Edit View

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-ui#15]
UX Feedback: https://bit.ly/3bk4HA3
-  I think Elliot's Point Point 4 falls here
-  Edit form and Submisson History (which is the edit history) should be on a single tab ( The edit process is 
-  Download icon and Full diff icon looks great, it can replace what is in the mock
-  We need to enforce consistent text alignment, all texts on the table should be aligned left including File names in the submission History 
-  Table Headings be also Aligned left and Bold black for all tables (submission, history, ...)
-  Tiny Upload button be replaced with dropzonejs as shown in the mock 
-  The full diff action dialog is excellent 
-  3 additional columns be added to the history table to display association, samples, .. count for each file history 

![4.jpg](https://images.zenhubusercontent.com/5f0f4126d974dfe9149c1910/6e97bab0-2ff4-4878-a201-ed405133fb2e)

**Comment by ala-ebi** [comment]
Note to self:
1. todo
2. okay
3. done
4. done
5. done, left both button and drop for large screens, button only for smaller screens
6. okay
7. done
