### ISSUE TITLE
Changes to Menu

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-ui#16]
- UX Feedback: https://bit.ly/3bk4HA3
- In addition to Elliots point 7:
- Bell icon be removed for now  
- 3 Menus at the top should go as the menu is still going to grow in number as we add more features
- In replacement Menu icon should be at top left as in mock, and vertical navigation menu should display when clicked
- GWAS icon be made bigger and clicked to GWAS Website 
- Vetical Padding of the top bar be reduced slightly

**Comment by ala-ebi** [comment]
Notes to self:
1. I think the indentation makes the title standout, and it is the default behaviour for the card headers. For now I havent changed. Logo now takes to the gwas catalog, removed unimplemented features' menu buttons. 
2. done.
3. done partially, waiting for response from Yomi slack.
4. waiting for response from Yomi slack.
5. done.
6. vertical padding reduced.

**Comment by ala-ebi** [comment]
centralise menu items
