### ISSUE TITLE
Create User Interface for the free text sample description feature .

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-ui#64]
Create User Interface for the free text sample description feature .

**Comment by sajo-ebi** [comment]
The UI should consist of table having 3 columns GCST , Initial Sample Desc & replication Sample Desc. Curators should have the ability to edit multiple study rows & submit using checkboxes for each row . The checkboxes selected will be submitted to the Backend API . Also there should be searchbox to do search on the GCST Id

@ljwh2 @sprintell can you please confirm on the above UI , we can setup a meeting to discuss further on the Ui specification

**Comment by ljwh2** [comment]
@sajo-ebi would be useful to have study tag displayed as well.

**Comment by eks-ebi** [comment]
Discussed in meeting today:

1. Samples page should display a table with 3 columns as above. In the first instance, the table does not need to be editable in-line within the UI.
2. There should be buttons on the same page to allow bulk changes to sample descriptions across all studies.
3. Curator clicks a button to download a tab-separated file displaying the current contents of the table: GCST, study tag, initial sample description and replication sample description. (to be edited off-line)
4. Curator clicks another button to upload the edited tab-separated file to upload bulk changes to the sample descriptions
5. Curator should receive a report summarising how many sample description strings have been changed, e.g. "Initial sample description changed for 200 studies. Replication sample description changed for 200 studies."

**Comment by sajo-ebi** [comment]
Hi @ala-ebi ,

The API for Sample Description are ready for UI to consume 

API has been created for getting Sample Description for submission & updating multiple studies with submssionId

Get Sample Description for Submission

[Get Sample Description for Submission](https://wwwdev.ebi.ac.uk/gwas/depo-curation/api/v1/submissions/{SubmissionId}/studies/sampledescription)

[Patch Sample Description for Submission](https://wwwdev.ebi.ac.uk/gwas/depo-curation/api/v1/submissions/{SubmissionId}/studies/sampledescription)


Method - GET

[Download Sample Descriptions for submission](https://wwwdev.ebi.ac.uk/gwas/depo-curation/api/v1/submissions/{SubmissionId}/studies/sampledescription/files)

Method - POST

[Upload Sample Descriptions for submission](https://wwwdev.ebi.ac.uk/gwas/depo-curation/api/v1/submissions/{SubmissionId}/studies/sampledescription/files)

**Comment by sajo-ebi** [comment]
Payload for Patch Sample Description

[
            {
                "GCST": "GCST90064588",
                "initialSampleDescription": "2,296 Kazakh, Uzbek ancestry cases, 3,000 Kazakh, Uzbek ancestry controls,6,500 European ancestry cases, 255,600 European ancestry controls, sajo",
                "replicateSampleDescription": "678 Kazakh ancestry cases, 250 Kazakh ancestry controls,2,043 European ancestry cases, 6,018 European ancestry controls, sajo",
                "studyTag": "Maternal meta"
            },

            {
                "GCST": "GCST90064587",
                "initialSampleDescription": "4,630 Uzbek ancestry cases, 373,345 Uzbek ancestry controls, sajo",
                "replicateSampleDescription": "580 European ancestry cases, 760 European ancestry controls, sajo",
                "studyTag": "Fetal European"
            },
            {
                "GCST": "GCST90064586",
                "initialSampleDescription": "1,500 Kazakh, Uzbek ancestry cases, 2,027 Kazakh, Uzbek ancestry controls, sajo",
                "replicateSampleDescription": "452 Kazakh ancestry cases, 361 Kazakh ancestry controls, sajo",
                "studyTag": "Fetal Central Asian"
            }
]

**Comment by ljwh2** [comment]
Deployed in Sandbox, import is failing
