### ISSUE TITLE
Publication Management Page to view, filter, and export publications in the curation app

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-ui#93]
**As a curator**
I need a publications management page similar to the Submission management page https://www.ebi.ac.uk/gwas/depo-curation/submissions

**Management Rules:**
Rule 1: A menu item should be added on the top bar of the curation app with label "Publications"
Rule 2: When the "Publications" Label is clicked on the menu, it should route to a url /publications
Rule 3: The view of the /publications page should contain a Paginated Tabular View of all publications in the database including those without associated submissions.
Rule 4: Columns of the Tabular View should include: PMID, First Author, Title, Submitter, Curator, Curation Status, Publication date. Where Publication date = Journal publication date as shown below

![Screenshot 2022-08-30 at 17.34.51.png](https://images.zenhubusercontent.com/5f0f4126d974dfe9149c1910/b0f94ce0-41a3-42bf-a63d-9352623d98fa)

Rule 5: Each PMID must be hyperlinked to a corresponding detailed Publication page
Rule 6: The table should have an Export button for exporting the publications
Rule 7: There should be Filter Button below the table similar to submission management page
Rule 8: Filter should include: pmid, title, curator
Rule 9: Curator Filter ui component should be a Typeahead Autosuggest search Box

**Comment by sajo-ebi** [comment]
@ala-ebi The PublicationAPI Details are -:

Url : http://wwwdev.ebi.ac.uk/gwas/depo-curation/api/v1/publications

Search params

` @JsonProperty("pmid")
    private String pmid;
    @JsonProperty("curator")
    private String curator;
    @JsonProperty("curationStatus")
    private String curationStatus;
    @JsonProperty("title")
    private String title;`

The CUrator API details are -:
Url -: http://wwwdev.ebi.ac.uk/gwas/depo-curation/api/v1/curators

The CUration Status API details are -:

Url -:  http://wwwdev.ebi.ac.uk/gwas/depo-curation/api/v1/curator-status

**Comment by ljwh2** [comment]
Feedback from testing is here: https://docs.google.com/document/d/1hlihpeERA0beyRoMJT5OvzIHWaJNRGjamxCdOvTSUy4/edit?usp=sharing

**Comment by sprintell** [comment]
@ala-ebi will complete the feature for refreshing the submitter dataset (This should be an API endpoint and should be documented)

**Comment by ala-ebi** [comment]
`PUT /api/v1/publications/utils/fill-submitter-for-old-publications`
